create extension if not exists pgcrypto;

create table if not exists categories (
 id uuid primary key default gen_random_uuid(),
 name text not null,
 slug text unique not null,
 description text,
 image_url text,
 active boolean not null default true,
 sort_order integer not null default 0,
 created_at timestamptz not null default now()
);

create table if not exists products (
 id uuid primary key default gen_random_uuid(),
 name text not null,
 slug text unique not null,
 description text,
 sku text,
 product_type text not null default 'standard' check (product_type in ('standard','personalized','dizecode')),
 price numeric(10,2) not null default 0,
 compare_at_price numeric(10,2),
 stock integer not null default 0,
 track_stock boolean not null default true,
 active boolean not null default true,
 featured boolean not null default false,
 badge text,
 category_id uuid references categories(id) on delete set null,
 personalization_enabled boolean not null default false,
 dizecode_enabled boolean not null default false,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);

create table if not exists product_images (
 id uuid primary key default gen_random_uuid(),
 product_id uuid not null references products(id) on delete cascade,
 image_url text not null,
 alt_text text,
 sort_order integer not null default 0,
 created_at timestamptz not null default now()
);

create table if not exists banners (
 id uuid primary key default gen_random_uuid(),
 title text,
 subtitle text,
 image_url text,
 mobile_image_url text,
 button_text text,
 button_url text,
 position text not null default 'home_hero',
 active boolean not null default true,
 sort_order integer not null default 0,
 starts_at timestamptz,
 ends_at timestamptz,
 created_at timestamptz not null default now()
);

create table if not exists promotions (
 id uuid primary key default gen_random_uuid(),
 name text not null,
 description text,
 discount_type text check (discount_type in ('percentage','fixed')),
 discount_value numeric(10,2),
 coupon_code text unique,
 active boolean not null default true,
 starts_at timestamptz,
 ends_at timestamptz,
 created_at timestamptz not null default now()
);

create table if not exists store_sections (
 id uuid primary key default gen_random_uuid(),
 section_key text unique not null,
 title text,
 subtitle text,
 content jsonb not null default '{}'::jsonb,
 active boolean not null default true,
 sort_order integer not null default 0,
 updated_at timestamptz not null default now()
);

create table if not exists orders (
 id uuid primary key default gen_random_uuid(),
 order_number bigint generated by default as identity unique,
 customer_name text,
 customer_email text,
 customer_phone text,
 status text not null default 'pending',
 payment_status text not null default 'pending',
 shipping_status text not null default 'pending',
 subtotal numeric(10,2) not null default 0,
 shipping_total numeric(10,2) not null default 0,
 discount_total numeric(10,2) not null default 0,
 total numeric(10,2) not null default 0,
 shipping_data jsonb not null default '{}'::jsonb,
 payment_data jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

create table if not exists order_items (
 id uuid primary key default gen_random_uuid(),
 order_id uuid not null references orders(id) on delete cascade,
 product_id uuid references products(id) on delete set null,
 product_name text not null,
 sku text,
 quantity integer not null default 1,
 unit_price numeric(10,2) not null,
 personalization jsonb not null default '{}'::jsonb,
 production_file_url text,
 preview_image_url text
);

alter table categories enable row level security;
alter table products enable row level security;
alter table product_images enable row level security;
alter table banners enable row level security;
alter table promotions enable row level security;
alter table store_sections enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

create policy "public read active categories" on categories for select using (active = true);
create policy "public read active products" on products for select using (active = true);
create policy "public read product images" on product_images for select using (true);
create policy "public read active banners" on banners for select using (active = true);
create policy "public read active promotions" on promotions for select using (active = true);
create policy "public read active sections" on store_sections for select using (active = true);
