'use client';
import {useState} from 'react';
import Link from 'next/link';
export default function Produto(){
 const [nome,setNome]=useState('Seu nome'); const [frase,setFrase]=useState('Um presente especial'); const [qr,setQr]=useState(false); const [foto,setFoto]=useState<string|null>(null); const [fileName,setFileName]=useState('');
 const [zoom,setZoom]=useState(100); const [posX,setPosX]=useState(50); const [posY,setPosY]=useState(50); const [fontSize,setFontSize]=useState(26); const [font,setFont]=useState('Arial'); const [textColor,setTextColor]=useState('#173d5a'); const [view,setView]=useState<'front'|'left'|'right'|'flat'>('front');
 function handlePhoto(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return;setFileName(f.name);const reader=new FileReader();reader.onload=()=>{setFoto(String(reader.result));setZoom(100);setPosX(50);setPosY(50)};reader.readAsDataURL(f)}
 const wrapPos=view==='left'?'0%':view==='right'?'100%':'50%';
 const photoStyle={objectPosition:`${view==='flat'?posX:wrapPos} ${posY}%`,transform:`scale(${zoom/100})`};
 const overlay=<><div className="liveText" style={{fontFamily:font,color:textColor,fontSize:fontSize}}><span>{frase}</span><b>{nome}</b></div>{qr&&<div className="realQr">▦<small>Escaneie</small></div>}</>;
 return <main><header><Link href="/" className="logo"><b>Cane</b><strong>Kids</strong></Link><nav><Link href="/">Início</Link><Link href="/carrinho">Sacola</Link></nav></header>
 <section className="productPage"><div className="productPreview realisticPreview"><div className="previewTitle"><span className="eyebrow">SIMULAÇÃO DA CANECA</span><b>Confira a arte inteira e cada lado da caneca</b><small>O arquivo de produção usa o gabarito de 20,5 × 9,5 cm.</small></div><div className="viewTabs"><button className={view==='left'?'active':''} onClick={()=>setView('left')}>Lado esquerdo</button><button className={view==='front'?'active':''} onClick={()=>setView('front')}>Frente / centro</button><button className={view==='right'?'active':''} onClick={()=>setView('right')}>Lado direito</button><button className={view==='flat'?'active':''} onClick={()=>setView('flat')}>Arte completa</button></div>
 {view==='flat'?<div className="flatTemplate"><div className="dimensionTop"><b>20,5 cm</b><span>área de impressão</span></div><div className="flatArt">{foto?<img className="templatePhoto" src={foto} alt="Arte completa enviada" style={photoStyle}/>:<div className="photoPlaceholder">＋<small>Sua arte 20,5 × 9,5 cm</small></div>}{overlay}<div className="guide g1"></div><div className="guide g2"></div></div><div className="flatMarks"><span>LADO ESQUERDO</span><b>FRENTE / CENTRO</b><span>LADO DIREITO</span></div><div className="heightMark">9,5 cm</div></div>:
 <div className={'realMugScene view-'+view}><div className="realMug"><div className="realMugHandle"></div><div className="curvedPrint">{foto?<img className="wrapPhoto" src={foto} alt="Arte aplicada à caneca" style={photoStyle}/>:<div className="photoPlaceholder">＋<small>Sua arte</small></div>}{overlay}<div className="curveShade leftShade"></div><div className="curveShade rightShade"></div><div className="ceramicGloss"></div></div></div><div className="sceneShadow"></div></div>}
 <div className="previewNote"><b>{view==='flat'?'Arquivo completo':'Prévia da caneca'}</b><span>{view==='flat'?'Aqui você vê 100% da arte na proporção real de impressão 20,5 × 9,5 cm, sem corte.':'Esta visão mostra somente a região da arte que fica visível neste ângulo. A imagem original continua inteira no gabarito.'}</span></div></div>
 <div className="config"><span className="eyebrow">PERSONALIZE DO SEU JEITO</span><h1>Caneca com a sua história</h1><p className="productLead">Envie uma arte pronta no gabarito 20,5 × 9,5 cm ou use uma foto e ajuste a composição.</p><div className="rating">★★★★★ <small>Confira frente, laterais e arte completa antes da produção</small></div><div className="price">R$ 39,90 <small>Pix ou cartão no checkout</small></div><div className="stepsMini"><span><b>1</b> Foto/arte</span><span><b>2</b> Ajuste</span><span><b>3</b> Texto</span><span><b>4</b> Conferir</span></div>
 <label className={'upload uploadReal '+(foto?'uploaded':'')}>1. Sua foto ou arte <input type="file" accept="image/png,image/jpeg,image/webp" onChange={handlePhoto}/><span>{foto?'✓ Trocar imagem':'＋ Escolher foto ou arte'}</span><small>{fileName||'Para arte completa, recomendamos a proporção 20,5 × 9,5 cm.'}</small></label>{foto&&<><button type="button" className="removePhoto" onClick={()=>{setFoto(null);setFileName('')}}>Remover foto</button><div className="editorPanel"><strong>2. Ajustar imagem</strong><p className="editorHint">Em 100%, a arte completa fica enquadrada no gabarito. Use zoom apenas se desejar ampliar.</p><label>Ampliar / diminuir <output>{zoom}%</output><input type="range" min="70" max="180" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label>Posição vertical <input type="range" min="0" max="100" value={posY} onChange={e=>setPosY(+e.target.value)}/></label><button type="button" onClick={()=>{setZoom(100);setPosX(50);setPosY(50)}}>Restaurar enquadramento</button></div></>}
 <div className="textEditor"><strong>3. Personalizar texto</strong><label>Nome <input value={nome} maxLength={28} onChange={e=>setNome(e.target.value)}/></label><label>Frase ou mensagem <textarea value={frase} maxLength={90} onChange={e=>setFrase(e.target.value)}/></label><div className="editorRow"><label>Fonte <select value={font} onChange={e=>setFont(e.target.value)}><option value="Arial">Clássica</option><option value="Georgia">Elegante</option><option value="cursive">Manuscrita</option><option value="Verdana">Moderna</option><option value="Trebuchet MS">Divertida</option></select></label><label>Cor <input className="colorInput" type="color" value={textColor} onChange={e=>setTextColor(e.target.value)}/></label></div><label>Tamanho do texto <output>{fontSize}px</output><input type="range" min="16" max="40" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/></label></div><label className="qrOption"><input type="checkbox" checked={qr} onChange={e=>setQr(e.target.checked)}/><span><b>Adicionar experiência DizeCode + R$ 9,90</b><small>Conecte a caneca a vídeo, fotos, áudio ou mensagem por QR Code.</small></span></label><Link className="buy" href={'/carrinho?nome='+encodeURIComponent(nome)+'&qr='+(qr?'1':'0')}>Adicionar à sacola • R$ {qr?'49,80':'39,90'}</Link><div className="safe">🔒 Compra segura &nbsp; ✓ Personalização conferida &nbsp; 🎁 Feito para presentear</div></div></section></main>
}