'use client';
import {useEffect,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Suspense} from 'react';
import {supabase} from '../../lib/supabase';
import Link from 'next/link';
import dynamic from 'next/dynamic';
const Mug360=dynamic(()=>import('../../components/Mug360'),{ssr:false});

const W=2050,H=950;
type Layout='side'|'stack'|'heroLeft'|'heroRight';
function slotsFor(n:number,layout:Layout){
 const g=24;
 if(n===1)return [{x:0,y:0,w:W,h:H}];
 if(layout==='stack')return Array.from({length:n},(_,i)=>({x:0,y:i*(H/n),w:W,h:H/n-(i<n-1?g:0)}));
 if(n===3&&layout==='heroLeft')return [{x:0,y:0,w:W*.56-g/2,h:H},{x:W*.56+g/2,y:0,w:W*.44-g/2,h:H/2-g/2},{x:W*.56+g/2,y:H/2+g/2,w:W*.44-g/2,h:H/2-g/2}];
 if(n===3&&layout==='heroRight')return [{x:0,y:0,w:W*.44-g/2,h:H/2-g/2},{x:0,y:H/2+g/2,w:W*.44-g/2,h:H/2-g/2},{x:W*.44+g/2,y:0,w:W*.56-g/2,h:H}];
 return Array.from({length:n},(_,i)=>({x:i*(W/n),y:0,w:W/n-(i<n-1?g:0),h:H}));
}
function buildComposition(photos:string[],layout:Layout,zooms:number[],xs:number[],ys:number[],done:(v:string|null)=>void){
 if(!photos.length){done(null);return}
 const canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);
 Promise.all(photos.map(src=>new Promise<HTMLImageElement>((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src}))).then(imgs=>{
  const slots=slotsFor(imgs.length,layout);
  imgs.forEach((im,i)=>{const s=slots[i];ctx.save();ctx.beginPath();ctx.rect(s.x,s.y,s.w,s.h);ctx.clip();const base=Math.min(s.w/im.naturalWidth,s.h/im.naturalHeight);const scale=base*((zooms[i]||100)/100);const dw=im.naturalWidth*scale,dh=im.naturalHeight*scale;const dx=s.x+(s.w-dw)*((xs[i]??50)/100),dy=s.y+(s.h-dh)*((ys[i]??50)/100);ctx.drawImage(im,dx,dy,dw,dh);ctx.restore()});done(canvas.toDataURL('image/jpeg',.94));
 }).catch(()=>done(null));
}

function ProdutoEditor(){
 const params=useSearchParams();const productId=params.get('id');const [catalogProduct,setCatalogProduct]=useState<any>(null);const [priceLoading,setPriceLoading]=useState(true);
 useEffect(()=>{let active=true;async function fetchPrice(){if(!supabase){if(active)setPriceLoading(false);return;}const r=await supabase.rpc('storefront_products');if(!active)return;const all=r.data||[];const selected=productId?all.find((p:any)=>String(p.id)===productId):all.find((p:any)=>p.tipo!=='comum'&&p.ativo!==false);setCatalogProduct(selected||null);setPriceLoading(false)}fetchPrice();return()=>{active=false}},[productId]);
 const price=Number(catalogProduct?.preco||0);const money=(v:number)=>'R$ '+v.toFixed(2).replace('.',',');
 const [nome,setNome]=useState('Seu nome'); const [frase,setFrase]=useState('Um presente especial'); const [qr,setQr]=useState(false); const surcharge=qr?9.90:0; const [photos,setPhotos]=useState<string[]>([]); const [fileNames,setFileNames]=useState<string[]>([]); const [printImage,setPrintImage]=useState<string|null>(null);
 const [layout,setLayout]=useState<Layout>('side'); const [selected,setSelected]=useState(0); const [zooms,setZooms]=useState([100,100,100]); const [xs,setXs]=useState([50,50,50]); const [ys,setYs]=useState([50,50,50]);
 const [fontSize,setFontSize]=useState(26); const [font,setFont]=useState('Arial'); const [textColor,setTextColor]=useState('#173d5a'); const [view,setView]=useState<'front'|'left'|'right'|'flat'>('front'); const [spin,setSpin]=useState(false);
 useEffect(()=>{buildComposition(photos,layout,zooms,xs,ys,setPrintImage)},[photos,layout,zooms,xs,ys]);
 function handlePhotos(e:React.ChangeEvent<HTMLInputElement>){const fs=Array.from(e.target.files||[]).slice(0,3);if(!fs.length)return;Promise.all(fs.map(f=>new Promise<string>(resolve=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.readAsDataURL(f)}))).then(srcs=>{setPhotos(srcs);setFileNames(fs.map(f=>f.name));setSelected(0);setLayout('side');setZooms([100,100,100]);setXs([50,50,50]);setYs([50,50,50])});e.target.value=''}
 function removePhoto(i:number){setPhotos(p=>p.filter((_,n)=>n!==i));setFileNames(p=>p.filter((_,n)=>n!==i));setSelected(0)}
 function change(arr:number[],setter:(v:number[])=>void,v:number){const next=[...arr];next[selected]=v;setter(next)}
 const angle=view==='left'?-Math.PI/2:view==='right'?Math.PI/2:0;
 const overlay=<><div className="liveText" style={{fontFamily:font,color:textColor,fontSize:fontSize}}><span>{frase}</span><b>{nome}</b></div>{qr&&<div className="realQr">▦<small>Escaneie</small></div>}</>;
 return <main><header><Link href="/" className="logo"><b>Cane</b><strong>Kids</strong></Link><nav><Link href="/">Início</Link><Link href="/carrinho">Sacola</Link></nav></header>
 <section className="productPage"><div className="productPreview realisticPreview"><div className="previewTitle"><span className="eyebrow">PRÉVIA INTERATIVA 360°</span><b>Veja sua arte contornando a caneca</b><small>A prévia 360° usa exatamente a mesma composição mostrada em Arte completa.</small></div><div className="viewTabs"><button className={view==='left'?'active':''} onClick={()=>{setSpin(false);setView('left')}}>Lado esquerdo</button><button className={view==='front'?'active':''} onClick={()=>{setSpin(false);setView('front')}}>Frente / centro</button><button className={view==='right'?'active':''} onClick={()=>{setSpin(false);setView('right')}}>Lado direito</button><button className={view==='flat'?'active':''} onClick={()=>{setSpin(false);setView('flat')}}>Arte completa</button></div>
 {view==='flat'?<div className="flatTemplate"><div className="dimensionTop"><b>20,5 cm</b><span>área de impressão</span></div><div className="flatArt">{printImage?<img className="templatePhoto" src={printImage} alt="Arte completa preparada para impressão"/>:<div className="photoPlaceholder">＋<small>Sua arte 20,5 × 9,5 cm</small></div>}{overlay}<div className="guide g1"></div><div className="guide g2"></div></div><div className="flatMarks"><span>LADO ESQUERDO</span><b>FRENTE / CENTRO</b><span>LADO DIREITO</span></div><div className="heightMark">9,5 cm</div></div>:<div className="viewer360"><Mug360 image={printImage} autoRotate={spin} targetAngle={angle}/><button className={'spinButton '+(spin?'active':'')} onClick={()=>setSpin(!spin)}>{spin?'Parar rotação':'↻ Girar automaticamente'}</button></div>}
 <div className="previewNote"><b>{view==='flat'?'Arquivo completo':'Visualização 360°'}</b><span>{view==='flat'?'Esta é a composição exata que será aplicada na caneca, na proporção 20,5 × 9,5 cm.':'A caneca recebe a mesma composição da Arte completa, sem esticar ou deformar as fotos.'}</span></div></div>
 <div className="config"><span className="eyebrow">PERSONALIZE DO SEU JEITO</span><h1>Caneca com a sua história</h1><p className="productLead">Envie uma arte pronta ou escolha até 3 fotos. Escolha a disposição e ajuste cada foto separadamente.</p><div className="rating">★★★★★ <small>Confira a caneca em 360° antes da produção</small></div><div className="price">{priceLoading?'Consultando preço...':catalogProduct?money(price):'Preço indisponível'} <small>Pagamento disponível após a ativação do checkout</small></div><div className="stepsMini"><span><b>1</b> Fotos/arte</span><span><b>2</b> Composição</span><span><b>3</b> Texto</span><span><b>4</b> Conferir</span></div>
 <label className={'upload uploadReal '+(photos.length?'uploaded':'')}>1. Sua arte ou até 3 fotos <input type="file" multiple accept="image/png,image/jpeg,image/webp" onChange={handlePhotos}/><span>{photos.length?'Trocar seleção':'Escolher arte ou fotos'}</span><small>{photos.length?`${photos.length} imagem(ns) selecionada(s) — máximo 3`:'Arte completa: 20,5 × 9,5 cm. Fotos comuns serão encaixadas sem deformação.'}</small></label>
 {photos.length>0&&<div style={{display:'grid',gridTemplateColumns:`repeat(${photos.length},1fr)`,gap:8,margin:'10px 0 14px'}}>{photos.map((p,i)=><div key={i} onClick={()=>setSelected(i)} style={{border:selected===i?'2px solid #087ac5':'1px solid #dce9ef',borderRadius:10,padding:7,textAlign:'center',cursor:'pointer'}}><img src={p} alt={`Foto ${i+1}`} style={{width:'100%',height:72,objectFit:'contain',background:'#f7f9fa',borderRadius:6}}/><small style={{display:'block',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',margin:'5px 0'}}>{fileNames[i]}</small><button type="button" className="removePhoto" onClick={e=>{e.stopPropagation();removePhoto(i)}}>Remover</button></div>)}</div>}
 {photos.length>1&&<div className="editorPanel"><strong>2. Escolha a disposição</strong><p className="editorHint">Você pode colocar as fotos lado a lado, uma em cima da outra ou usar uma foto maior com duas menores.</p><div className="viewTabs" style={{justifyContent:'flex-start',marginTop:10}}><button className={layout==='side'?'active':''} onClick={()=>setLayout('side')}>Lado a lado</button><button className={layout==='stack'?'active':''} onClick={()=>setLayout('stack')}>Uma embaixo da outra</button>{photos.length===3&&<><button className={layout==='heroLeft'?'active':''} onClick={()=>setLayout('heroLeft')}>1 grande + 2 à direita</button><button className={layout==='heroRight'?'active':''} onClick={()=>setLayout('heroRight')}>2 à esquerda + 1 grande</button></>}</div></div>}
 {photos.length>0&&<div className="editorPanel"><strong>{photos.length>1?`3. Ajustar foto ${selected+1}`:'2. Ajustar imagem'}</strong><p className="editorHint">Clique na miniatura da foto que deseja editar. Zoom e posição são independentes para cada imagem.</p><label>Ampliar / diminuir <output>{zooms[selected]}%</output><input type="range" min="70" max="220" value={zooms[selected]} onChange={e=>change(zooms,setZooms,+e.target.value)}/></label><label>Posição horizontal <input type="range" min="0" max="100" value={xs[selected]} onChange={e=>change(xs,setXs,+e.target.value)}/></label><label>Posição vertical <input type="range" min="0" max="100" value={ys[selected]} onChange={e=>change(ys,setYs,+e.target.value)}/></label><button type="button" onClick={()=>{change(zooms,setZooms,100);change(xs,setXs,50);change(ys,setYs,50)}}>Restaurar esta foto</button></div>}
 <div className="textEditor"><strong>Personalizar texto</strong><label>Nome <input value={nome} maxLength={28} onChange={e=>setNome(e.target.value)}/></label><label>Frase ou mensagem <textarea value={frase} maxLength={90} onChange={e=>setFrase(e.target.value)}/></label><div className="editorRow"><label>Fonte <select value={font} onChange={e=>setFont(e.target.value)}><option value="Arial">Clássica</option><option value="Georgia">Elegante</option><option value="cursive">Manuscrita</option><option value="Verdana">Moderna</option><option value="Trebuchet MS">Divertida</option></select></label><label>Cor <input className="colorInput" type="color" value={textColor} onChange={e=>setTextColor(e.target.value)}/></label></div><label>Tamanho do texto <output>{fontSize}px</output><input type="range" min="16" max="40" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/></label></div><label className="qrOption"><input type="checkbox" checked={qr} onChange={e=>setQr(e.target.checked)}/><span><b>Adicionar experiência DizeCode + R$ 9,90</b><small>Conecte a caneca a vídeo, fotos, áudio ou mensagem por QR Code.</small></span></label>{catalogProduct?<Link className="buy" href={'/carrinho?produto='+encodeURIComponent(catalogProduct.id)+'&nome='+encodeURIComponent(nome)+'&qr='+(qr?'1':'0')}>Adicionar à sacola • {money(price+surcharge)}</Link>:<div className="buy" style={{background:'#8fa5b4'}}>Selecione um produto personalizado cadastrado</div>}<div className="safe">Compra segura · Personalização conferida · Feito para presentear</div></div></section></main>
}
export default function Produto(){return <Suspense fallback={<main style={{padding:40}}>Carregando personalizador...</main>}><ProdutoEditor/></Suspense>}
