'use client';
import {useState} from 'react';
import Link from 'next/link';
export default function Produto(){
 const [nome,setNome]=useState('Seu nome'); const [frase,setFrase]=useState('Um presente especial'); const [qr,setQr]=useState(false); const [foto,setFoto]=useState<string|null>(null); const [fileName,setFileName]=useState('');
 const [zoom,setZoom]=useState(100); const [posX,setPosX]=useState(50); const [posY,setPosY]=useState(50); const [fontSize,setFontSize]=useState(26); const [font,setFont]=useState('Arial'); const [textColor,setTextColor]=useState('#173d5a');
 function handlePhoto(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return;setFileName(f.name);const reader=new FileReader();reader.onload=()=>{setFoto(String(reader.result));setZoom(100);setPosX(50);setPosY(50)};reader.readAsDataURL(f)}
 return <main><header><Link href="/" className="logo"><b>Cane</b><strong>Kids</strong></Link><nav><Link href="/">Início</Link><Link href="/carrinho">Sacola</Link></nav></header>
 <section className="productPage"><div className="productPreview realisticPreview"><div className="previewTitle"><span className="eyebrow">SIMULAÇÃO DO PRODUTO</span><b>Veja como sua caneca pode ficar</b><small>Prévia aproximada para ajudar na personalização</small></div><div className="realMugScene"><div className="realMug"><div className="realMugHandle"></div><div className="printArea">{foto?<img src={foto} alt="Foto enviada" style={{transform:`scale(${zoom/100})`,objectPosition:`${posX}% ${posY}%`}}/>:<div className="photoPlaceholder">＋<small>Sua foto</small></div>}<div className="liveText" style={{fontFamily:font,color:textColor,fontSize:fontSize}}><span>{frase}</span><b>{nome}</b></div>{qr&&<div className="realQr">▦<small>Escaneie</small></div>}</div></div><div className="sceneShadow"></div></div><div className="previewNote"><b>Prévia em tempo real</b><span>Use os controles ao lado para ampliar e reposicionar sua foto. A curvatura e as cores podem variar levemente no produto físico.</span></div></div>
 <div className="config"><span className="eyebrow">PERSONALIZE DO SEU JEITO</span><h1>Caneca com a sua história</h1><p className="productLead">Envie sua imagem e ajuste a composição enquanto visualiza uma simulação da caneca real.</p><div className="rating">★★★★★ <small>Você confere a personalização antes da produção</small></div><div className="price">R$ 39,90 <small>Pix ou cartão no checkout</small></div>
 <div className="stepsMini"><span><b>1</b> Foto</span><span><b>2</b> Ajuste</span><span><b>3</b> Texto</span><span><b>4</b> Finalizar</span></div>
 <label className={'upload uploadReal '+(foto?'uploaded':'')}>1. Sua foto ou arte <input type="file" accept="image/png,image/jpeg,image/webp" onChange={handlePhoto}/><span>{foto?'✓ Trocar imagem':'＋ Escolher foto do celular ou computador'}</span><small>{fileName||'PNG, JPG ou WEBP. A imagem aparecerá na caneca.'}</small></label>
 {foto&&<><button type="button" className="removePhoto" onClick={()=>{setFoto(null);setFileName('')}}>Remover foto</button><div className="editorPanel"><strong>2. Ajustar foto</strong><label>Ampliar / diminuir <output>{zoom}%</output><input type="range" min="70" max="180" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label>Mover para os lados <input type="range" min="0" max="100" value={posX} onChange={e=>setPosX(+e.target.value)}/></label><label>Mover para cima / baixo <input type="range" min="0" max="100" value={posY} onChange={e=>setPosY(+e.target.value)}/></label><button type="button" onClick={()=>{setZoom(100);setPosX(50);setPosY(50)}}>Centralizar imagem</button></div></>}
 <div className="textEditor"><strong>3. Personalizar texto</strong><label>Nome <input value={nome} maxLength={28} onChange={e=>setNome(e.target.value)}/></label><label>Frase ou mensagem <textarea value={frase} maxLength={90} onChange={e=>setFrase(e.target.value)}/></label><div className="editorRow"><label>Fonte <select value={font} onChange={e=>setFont(e.target.value)}><option value="Arial">Clássica</option><option value="Georgia">Elegante</option><option value="cursive">Manuscrita</option><option value="Verdana">Moderna</option><option value="Trebuchet MS">Divertida</option></select></label><label>Cor <input className="colorInput" type="color" value={textColor} onChange={e=>setTextColor(e.target.value)}/></label></div><label>Tamanho do texto <output>{fontSize}px</output><input type="range" min="16" max="40" value={fontSize} onChange={e=>setFontSize(+e.target.value)}/></label></div>
 <label className="qrOption"><input type="checkbox" checked={qr} onChange={e=>setQr(e.target.checked)}/><span><b>Adicionar experiência DizeCode + R$ 9,90</b><small>Conecte a caneca a vídeo, fotos, áudio ou mensagem por QR Code.</small></span></label><Link className="buy" href={'/carrinho?nome='+encodeURIComponent(nome)+'&qr='+(qr?'1':'0')}>Adicionar à sacola • R$ {qr?'49,80':'39,90'}</Link><div className="safe">🔒 Compra segura &nbsp; ✓ Personalização conferida &nbsp; 🎁 Feito para presentear</div></div></section></main>
}