'use client';
import Link from 'next/link';
import {useState} from 'react';
import {supabaseConfigured} from '../../lib/supabase';

const modules=[
 {title:'Produtos',text:'Cadastre produtos comuns, personalizados ou com DizeCode.',href:'/admin/produtos'},
 {title:'Categorias',text:'Organize canecas e futuras linhas de produtos.',href:'/admin/categorias'},
 {title:'Banners e vitrine',text:'Troque campanhas, imagens, chamadas e destaques da Home.',href:'/admin/banners'},
 {title:'Promoções',text:'Prepare descontos, campanhas e cupons.',href:'/admin/promocoes'},
 {title:'Pedidos',text:'Acompanhe pagamento, produção, frete e entrega.',href:'/admin/pedidos'},
 {title:'Configurações',text:'Dados da loja, integrações, pagamento e frete.',href:'/admin/configuracoes'}
];
export default function Admin(){const [open,setOpen]=useState(false);return <main style={{background:'#f6f8fb',minHeight:'100vh',color:'#123b59'}}><header style={{background:'#fff',padding:'20px 5%',display:'flex',justifyContent:'space-between',alignItems:'center',borderBottom:'1px solid #dbe5ec'}}><Link href="/" className="logo"><b>Cane</b><strong>Kids</strong></Link><div style={{display:'flex',gap:18,alignItems:'center'}}><Link href="/">Ver loja</Link><button onClick={()=>setOpen(!open)} style={{border:'1px solid #cbdbe6',background:'#fff',padding:'10px 16px',borderRadius:10}}>Administrador</button></div></header><section style={{maxWidth:1180,margin:'0 auto',padding:'52px 24px'}}><span className="eyebrow">PAINEL DA LOJA</span><h1 style={{fontSize:42,margin:'8px 0 10px'}}>Administração CaneKids</h1><p style={{maxWidth:720,fontSize:17,color:'#60788a'}}>Gerencie o conteúdo e a operação da loja sem alterar o código. Produtos, campanhas e imagens ficarão separados da programação do site.</p>{!supabaseConfigured&&<div style={{margin:'28px 0',padding:18,border:'1px solid #f1cf8c',background:'#fff9ec',borderRadius:12}}><b>Banco de dados aguardando conexão.</b><div style={{marginTop:6}}>A estrutura já está preparada. Falta configurar as variáveis NEXT_PUBLIC_SUPABASE_URL e NEXT_PUBLIC_SUPABASE_ANON_KEY na Vercel e executar o schema do projeto no Supabase.</div></div>}<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:18,marginTop:34}}>{modules.map(m=><Link key={m.title} href={m.href} style={{background:'#fff',padding:24,border:'1px solid #dbe5ec',borderRadius:16,minHeight:150,textDecoration:'none',color:'inherit'}}><h2 style={{margin:'0 0 10px',fontSize:21}}>{m.title}</h2><p style={{margin:0,color:'#60788a',lineHeight:1.5}}>{m.text}</p></Link>)}</div><section style={{background:'#fff',border:'1px solid #dbe5ec',borderRadius:16,padding:26,marginTop:28}}><h2 style={{marginTop:0}}>Estrutura preparada</h2><p>O catálogo aceita produto comum, personalizável e DizeCode. A Home poderá receber banners, promoções e seções administráveis. O personalizador 360° permanece como módulo específico dos produtos que utilizarem essa função.</p></section></section></main>}
