'use client';
import Link from 'next/link';
import {useState} from 'react';

export default function ProdutosAdmin(){
 const [form,setForm]=useState({nome:'',preco:'',tipo:'comum',categoria:'Canecas',estoque:'',imagem:'',ativo:true});
 const [salvos,setSalvos]=useState<any[]>([]);
 function change(e:any){const {name,value,type,checked}=e.target;setForm({...form,[name]:type==='checkbox'?checked:value});}
 function salvar(e:any){e.preventDefault();if(!form.nome||!form.preco)return;setSalvos([{...form,id:Date.now()},...salvos]);setForm({nome:'',preco:'',tipo:'comum',categoria:'Canecas',estoque:'',imagem:'',ativo:true});}
 return <main style={{minHeight:'100vh',background:'#f6f8fb',color:'#123b59'}}>
  <header style={{background:'#fff',borderBottom:'1px solid #dbe5ec',padding:'18px 5%',display:'flex',justifyContent:'space-between',alignItems:'center'}}><Link href="/admin" style={{fontWeight:800,fontSize:22,color:'#123b59',textDecoration:'none'}}>CaneKids Admin</Link><div style={{display:'flex',gap:18}}><Link href="/admin">Painel</Link><Link href="/">Ver loja</Link></div></header>
  <section style={{maxWidth:1180,margin:'0 auto',padding:'42px 24px'}}><p style={{fontWeight:800,color:'#087bc1',letterSpacing:1.5,fontSize:12}}>CATÁLOGO</p><h1 style={{fontSize:38,margin:'5px 0 8px'}}>Produtos</h1><p style={{color:'#60788a',maxWidth:720}}>Cadastre canecas prontas, produtos personalizáveis e produtos com experiência DizeCode. Esta tela já deixa o painel preparado para receber novos tipos de produtos no futuro.</p>
  <div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(320px,420px)',gap:24,alignItems:'start',marginTop:28}}>
   <section style={{background:'#fff',border:'1px solid #dbe5ec',borderRadius:16,padding:24}}><h2 style={{marginTop:0}}>Produtos cadastrados</h2>{salvos.length===0?<div style={{padding:'34px 10px',color:'#60788a',borderTop:'1px solid #edf2f5'}}>Nenhum produto cadastrado nesta sessão. Use o formulário ao lado para adicionar o primeiro.</div>:salvos.map(p=><div key={p.id} style={{display:'flex',gap:16,padding:'16px 0',borderTop:'1px solid #edf2f5',alignItems:'center'}}>{p.imagem?<img src={p.imagem} alt="" style={{width:72,height:72,objectFit:'cover',borderRadius:10,border:'1px solid #dbe5ec'}}/>:<div style={{width:72,height:72,borderRadius:10,background:'#f2f5f7',display:'grid',placeItems:'center',fontSize:12}}>Sem foto</div>}<div style={{flex:1}}><b>{p.nome}</b><div style={{color:'#60788a',marginTop:5}}>{p.categoria} · {p.tipo}</div></div><b>R$ {Number(String(p.preco).replace(',','.')).toFixed(2).replace('.',',')}</b></div>)}</section>
   <form onSubmit={salvar} style={{background:'#fff',border:'1px solid #dbe5ec',borderRadius:16,padding:24}}><h2 style={{marginTop:0}}>Novo produto</h2><Field label="Nome do produto"><input name="nome" value={form.nome} onChange={change} required style={input}/></Field><Field label="Preço"><input name="preco" value={form.preco} onChange={change} placeholder="39,90" required style={input}/></Field><Field label="Tipo"><select name="tipo" value={form.tipo} onChange={change} style={input}><option value="comum">Produto comum</option><option value="personalizavel">Personalizável</option><option value="dizecode">Personalizável + DizeCode</option></select></Field><Field label="Categoria"><input name="categoria" value={form.categoria} onChange={change} style={input}/></Field><Field label="Estoque"><input name="estoque" type="number" min="0" value={form.estoque} onChange={change} style={input}/></Field><Field label="URL da imagem"><input name="imagem" value={form.imagem} onChange={change} placeholder="https://..." style={input}/></Field><label style={{display:'flex',gap:9,alignItems:'center',margin:'16px 0'}}><input type="checkbox" name="ativo" checked={form.ativo} onChange={change}/> Produto ativo na loja</label><button type="submit" style={{width:'100%',border:0,borderRadius:10,padding:'14px 18px',fontWeight:800,background:'#087bc1',color:'#fff',cursor:'pointer'}}>Cadastrar produto</button><p style={{fontSize:12,color:'#60788a',lineHeight:1.45}}>Nesta primeira etapa o cadastro é visual/local. A persistência definitiva será ligada às tabelas do Supabase na próxima etapa.</p></form>
  </div></section>
 </main>
}
function Field({label,children}:any){return <label style={{display:'block',fontWeight:700,margin:'14px 0 6px'}}>{label}<div style={{marginTop:6}}>{children}</div></label>}
const input={width:'100%',boxSizing:'border-box' as const,padding:'12px 13px',border:'1px solid #cbdbe6',borderRadius:9,fontSize:15,background:'#fff'};
