'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
const vazio={nome:'',codigo:'',tipo:'percentual',valor:'',minimo:'0',ativo:true,inicio:'',fim:''};
export default function Promocoes(){
 const [form,setForm]=useState<any>(vazio),[items,setItems]=useState<any[]>([]),[editando,setEditando]=useState<string|null>(null),[msg,setMsg]=useState('');
 useEffect(()=>{carregar()},[]);
 async function carregar(){if(!supabase)return;const {data,error}=await supabase.rpc('admin_list_promotions');if(error)setMsg(error.message);else setItems(data||[])}
 function change(e:any){const {name,value,type,checked}=e.target;setForm((f:any)=>({...f,[name]:type==='checkbox'?checked:value}))}
 async function salvar(e:any){e.preventDefault();if(!supabase)return;const {error}=await supabase.rpc('admin_save_promotion',{p_id:editando,p_nome:form.nome,p_codigo:form.codigo,p_tipo:form.tipo,p_valor:Number(String(form.valor).replace(',','.')),p_minimo:Number(String(form.minimo||0).replace(',','.')),p_ativo:form.ativo,p_inicio:form.inicio?new Date(form.inicio).toISOString():null,p_fim:form.fim?new Date(form.fim).toISOString():null});if(error)setMsg('Não foi possível salvar: '+error.message);else{setMsg('Promoção salva.');setForm(vazio);setEditando(null);carregar()}}
 function editar(p:any){const dt=(v:any)=>v?new Date(v).toISOString().slice(0,16):'';setEditando(p.id);setForm({nome:p.nome,codigo:p.codigo||'',tipo:p.tipo,valor:String(p.valor).replace('.',','),minimo:String(p.minimo).replace('.',','),ativo:p.ativo,inicio:dt(p.inicio),fim:dt(p.fim)})}
 async function excluir(id:string){if(!supabase||!confirm('Excluir esta promoção?'))return;const {error}=await supabase.rpc('admin_delete_promotion',{p_id:id});if(error)setMsg(error.message);else carregar()}
 return <main style={{minHeight:'100vh',background:'#f6f8fb',color:'#123b59'}}><header style={header}><Link href="/admin" style={brand}>CaneKids Admin</Link><Link href="/">Ver loja</Link></header><section style={{maxWidth:1120,margin:'0 auto',padding:'42px 24px'}}><p style={eyebrow}>VENDAS</p><h1 style={{fontSize:38,margin:'5px 0'}}>Promoções</h1><p style={{color:'#60788a'}}>Crie cupons e descontos com período de validade e valor mínimo.</p>{msg&&<div style={notice}>{msg}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr 400px',gap:24,alignItems:'start',marginTop:24}}><section style={card}><h2 style={{marginTop:0}}>Promoções cadastradas</h2>{items.length===0?<p style={{color:'#60788a'}}>Nenhuma promoção cadastrada.</p>:items.map(p=><div key={p.id} style={row}><div style={{flex:1}}><b>{p.nome}</b><div style={{fontSize:13,color:'#60788a',marginTop:4}}>{p.codigo?'Cupom '+p.codigo:'Desconto automático'} · {p.tipo==='percentual'?p.valor+'%':'R$ '+Number(p.valor).toFixed(2).replace('.',',')}</div><div style={{fontSize:12,marginTop:4}}>{p.ativo?'Ativa':'Desativada'} · mínimo R$ {Number(p.minimo).toFixed(2).replace('.',',')}</div></div><button onClick={()=>editar(p)} style={button}>Editar</button><button onClick={()=>excluir(p.id)} style={{...button,color:'#b42318'}}>Excluir</button></div>)}</section><form onSubmit={salvar} style={card}><h2 style={{marginTop:0}}>{editando?'Editar promoção':'Nova promoção'}</h2><Field label="Nome da campanha"><input name="nome" value={form.nome} onChange={change} required style={input}/></Field><Field label="Código do cupom (opcional)"><input name="codigo" value={form.codigo} onChange={change} placeholder="EX: BEMVINDO10" style={input}/></Field><div style={two}><Field label="Tipo"><select name="tipo" value={form.tipo} onChange={change} style={input}><option value="percentual">Percentual (%)</option><option value="fixo">Valor fixo (R$)</option></select></Field><Field label="Desconto"><input name="valor" value={form.valor} onChange={change} required placeholder="10" style={input}/></Field></div><Field label="Pedido mínimo (R$)"><input name="minimo" value={form.minimo} onChange={change} style={input}/></Field><div style={two}><Field label="Início"><input type="datetime-local" name="inicio" value={form.inicio} onChange={change} style={input}/></Field><Field label="Fim"><input type="datetime-local" name="fim" value={form.fim} onChange={change} style={input}/></Field></div><label style={check}><input type="checkbox" name="ativo" checked={form.ativo} onChange={change}/> Promoção ativa</label><button style={primary}>{editando?'Salvar alterações':'Criar promoção'}</button>{editando&&<button type="button" onClick={()=>{setEditando(null);setForm(vazio)}} style={{...button,width:'100%',marginTop:8}}>Cancelar</button>}</form></div></section></main>}
function Field({label,children}:any){return <label style={{display:'block',fontWeight:700,margin:'13px 0 6px'}}>{label}<div style={{marginTop:6}}>{children}</div></label>}
const header={padding:'18px 5%',background:'#fff',borderBottom:'1px solid #dbe5ec',display:'flex',justifyContent:'space-between'};const brand={fontWeight:800,color:'#123b59',textDecoration:'none'};const eyebrow={fontWeight:800,color:'#087bc1',letterSpacing:1.5,fontSize:12};const card={background:'#fff',border:'1px solid #dbe5ec',borderRadius:16,padding:22};const row={display:'flex',gap:9,alignItems:'center',padding:'15px 0',borderTop:'1px solid #edf2f5'};const input={width:'100%',boxSizing:'border-box' as const,padding:'11px 12px',border:'1px solid #cbdbe6',borderRadius:9,fontSize:14};const button={border:'1px solid #cbdbe6',borderRadius:8,padding:'8px 10px',background:'#fff',cursor:'pointer'};const primary={width:'100%',border:0,borderRadius:10,padding:'14px',fontWeight:800,background:'#087bc1',color:'#fff',cursor:'pointer'};const notice={marginTop:18,padding:'12px 14px',background:'#eef7fc',border:'1px solid #c9e4f4',borderRadius:10};const two={display:'grid',gridTemplateColumns:'1fr 1fr',gap:10};const check={display:'flex',gap:8,margin:'15px 0',fontWeight:600};