'use client';
import Link from 'next/link';
const categories=['Mais vendidos','Para Pai','Para Mãe','Casal','Família','Infantil','Pets','Profissões','Com QR Code'];
const products=[{icon:'☕',badge:'MAIS VENDIDO',title:'Caneca Sua Foto',text:'Sua foto, nome e mensagem.',price:'R$ 39,90',action:'Personalizar'},{icon:'♥',badge:'PRESENTE',title:'Caneca Pai Especial',text:'Modelo pronto para presentear e personalizar.',price:'R$ 44,90',action:'Ver produto'},{icon:'👩',badge:'PRESENTE',title:'Caneca Mãe, Meu Amor',text:'Uma lembrança pronta para emocionar.',price:'R$ 44,90',action:'Ver produto'},{icon:'🐾',badge:'PET',title:'Caneca Amor de Pet',text:'Personalize com foto e nome do seu pet.',price:'R$ 44,90',action:'Personalizar'},{icon:'💑',badge:'CASAL',title:'Caneca Nossa História',text:'Para datas especiais e momentos a dois.',price:'R$ 44,90',action:'Ver produto'},{icon:'🎓',badge:'PROFISSÕES',title:'Caneca Profissão',text:'Modelos para professores e diversas profissões.',price:'R$ 39,90',action:'Ver modelos'},{icon:'🎁',badge:'PERSONALIZE',title:'Crie do seu jeito',text:'Envie sua arte, foto, frase ou ideia.',price:'R$ 39,90',action:'Criar agora'},{icon:'▦',badge:'DIFERENCIAL CANEKIDS',title:'Presente com QR Code',text:'Conecte o presente a vídeo, fotos, áudio ou mensagem.',price:'a partir de R$ 49,80',action:'Criar experiência'}];
export default function Home(){return <main><div className="top">Presentes personalizados • Frete para todo o Brasil • Atendimento humano</div><header><Link href="/" className="logo"><b>Cane</b><strong>Kids</strong></Link><nav><a href="#vitrine">Produtos</a><a href="#categorias">Ocasiões</a><a href="#qr">Com QR Code</a><a href="#como">Como funciona</a><a href="#contato">Atendimento</a></nav><Link className="cart" href="/carrinho">Sacola</Link></header>
<section className="hero storeHero"><div className="heroText"><span className="pill">PRESENTES PARA FAZER PARTE DA HISTÓRIA</span><h1>Encontre um presente. <em>Deixe ele único.</em></h1><p>Escolha entre modelos prontos ou personalize com fotos, nomes e mensagens. E, quando quiser surpreender ainda mais, adicione uma experiência por QR Code.</p><div className="actions"><a className="primary" href="#vitrine">Ver canecas</a><Link className="secondary" href="/produto">Criar do meu jeito</Link></div><div className="benefits"><span>✓ Modelos prontos</span><span>✓ Personalização opcional</span><span>✓ QR Code interativo</span></div></div><div className="visual"><div className="blob"></div><div className="mug"><div className="handle"></div><div className="print">Um presente<br/><b>só de vocês</b><small>♥</small></div></div></div></section>
<section className="categoryStrip" id="categorias"><h2>Para quem é o presente?</h2><div>{categories.map((c,i)=><a href="#vitrine" key={c}><span>{['★','👨','👩','♥','🏠','🎈','🐾','✦','▦'][i]}</span>{c}</a>)}</div></section>
<section className="products storefront" id="vitrine"><span className="eyebrow">ESCOLHA, PERSONALIZE E PRESENTEIE</span><h2>Presentes para todos os momentos.</h2><p className="intro">Você pode comprar um modelo pronto ou transformar cada produto em algo exclusivamente seu.</p><div className="grid storeGrid">{products.map((p,i)=><article key={p.title}><div className={'pic p'+(i%4)}><span>{p.icon}</span><i>{p.badge}</i></div><div className="cardBody"><h3>{p.title}</h3><p>{p.text}</p><small>{p.price}</small><Link href="/produto">{p.action} →</Link></div></article>)}</div><Link className="showAll" href="/produto">Ver todas as canecas</Link></section>
<section className="qr qrFeature" id="qr"><div><span className="eyebrow">EXCLUSIVO CANEKIDS + DIZECODE</span><h2>O presente termina na embalagem. A experiência não.</h2><p>Adicione um QR Code ao produto e surpreenda com um vídeo, uma sequência de fotos, um áudio ou uma mensagem especial.</p><Link className="primary inlineBtn" href="/produto">Criar presente com QR</Link></div><div className="qrDemo"><div className="qrbox">▦</div><div><b>1. Presenteie</b><p>O QR vai aplicado ao produto.</p><b>2. Escaneie</b><p>Não precisa instalar aplicativo.</p><b>3. Emocione</b><p>Vídeo, fotos, áudio ou mensagem aparecem no celular.</p></div></div></section>
<section className="mockupVideo"><div className="mockupVideoText"><span className="eyebrow">VEJA COMO FICA NA VIDA REAL</span><h2>Da personalização para o presente.</h2><p>Veja um exemplo em movimento de como a arte ganha vida no produto. Você personaliza, confere a prévia e recebe uma caneca feita para presentear.</p><Link className="primary inlineBtn" href="/produto">Personalizar minha caneca</Link></div><div className="videoFrame"><video controls playsInline preload="metadata" poster="/video-poster.jpg"><source src="/canekids-mockup.mp4" type="video/mp4"/>Seu navegador não suporta vídeo.</video><span>Mockup demonstrativo do produto personalizado</span></div></section>
<section className="how" id="como"><div><span className="eyebrow">COMPRAR É SIMPLES</span><h2>Pronto ou personalizado. Você escolhe.</h2><p>Encontre um modelo na vitrine ou comece uma personalização. Antes de produzir, a arte personalizada poderá ser conferida.</p></div><ol><li><b>1</b><span><strong>Escolha o presente</strong>Navegue por pessoa, ocasião ou estilo.</span></li><li><b>2</b><span><strong>Personalize se quiser</strong>Adicione foto, nome, frase e QR Code.</span></li><li><b>3</b><span><strong>Confira os detalhes</strong>Revise a personalização antes da produção.</span></li><li><b>4</b><span><strong>Receba em casa</strong>Escolha a melhor opção de entrega para seu CEP.</span></li></ol></section>
<section className="shipping"><div><span>🚚</span><h3>Entrega para todo o Brasil</h3><p>Consulte opções de frete pelo CEP antes de finalizar.</p></div><div><span>✓</span><h3>Personalização conferida</h3><p>Mais segurança para produzir o presente do jeito que você imaginou.</p></div><div><span>💬</span><h3>Atendimento humano</h3><p>Se precisar, fale com uma pessoa para ajudar no seu pedido.</p></div></section>
<section className="cta" id="contato"><h2>Não encontrou o que imaginou?</h2><p>Conte sua ideia. A CaneKids pode ajudar a transformar em um presente personalizado.</p><a href="https://wa.me/5541998621723">Falar com a CaneKids no WhatsApp</a></section><footer><div className="logo"><b>Cane</b><strong>Kids</strong></div><p>Presentes, canecas e personalizados para guardar momentos.</p><small>© 2026 CaneKids • Brasil</small></footer></main>}