'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {supabase} from '../lib/supabase';
export default function Home(){
 const [products,setProducts]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[banners,setBanners]=useState<any[]>([]);
 useEffect(()=>{async function load(){if(!supabase)return;const [p,c,b]=await Promise.all([supabase.rpc('storefront_products'),supabase.rpc('storefront_categories'),supabase.rpc('storefront_banners')]);setProducts(p.data||[]);setCategories(c.data||[]);setBanners(b.data||[])}load()},[]);
 const banner=banners[0];
 return <main><div className="trustBar"><span>Frete para todo o Brasil</span><span>Compra segura</span><span>Personalize do seu jeito</span><span>Presentes que emocionam</span></div><header className="storeHeader"><Link href="/" className="logo"><b>Cane</b><strong>Kids</strong></Link><div className="storeSearch">O que você está procurando?<b>Buscar</b></div><nav><a href="#vitrine">Produtos</a><a href="#categorias">Categorias</a><a href="#qr">Com QR Code</a><a href="#como">Como funciona</a><a href="#contato">Atendimento</a></nav><Link className="cart" href="/carrinho">Sacola</Link></header>
 <section className="hero storeHero"><div className="heroText"><span className="pill">{banner?.etiqueta||'PRESENTES PARA FAZER PARTE DA HISTÓRIA'}</span><h1>{banner?.titulo||<>Encontre um presente. <em>Deixe ele único.</em></>}</h1><p>{banner?.subtitulo||'Escolha entre modelos prontos ou personalize com fotos, nomes e mensagens. E, quando quiser surpreender ainda mais, adicione uma experiência por QR Code.'}</p><div className="actions"><a className="primary" href={banner?.link_botao||'#vitrine'}>{banner?.texto_botao||'Ver produtos'}</a><Link className="secondary" href="/produto">Criar do meu jeito</Link></div><div className="benefits"><span>✓ Modelos prontos</span><span>✓ Personalização opcional</span><span>✓ QR Code interativo</span></div></div><div className="visual">{banner?.imagem?<img src={banner.imagem} alt={banner.titulo} style={{width:'100%',maxHeight:430,objectFit:'cover',borderRadius:24}}/>:<><div className="blob"></div><div className="mug"><div className="handle"></div><div className="print">Um presente<br/><b>só de vocês</b></div></div></>}</div></section>
 <section className="categoryStrip" id="categorias"><h2>Explore por categoria</h2><div>{categories.length?categories.map(c=><a href="#vitrine" key={c.id}>{c.nome}</a>):<a href="#vitrine">Canecas</a>}</div></section>
 <section className="products storefront" id="vitrine"><span className="eyebrow">ESCOLHA, PERSONALIZE E PRESENTEIE</span><h2>Presentes para todos os momentos.</h2><p className="intro">Escolha um modelo pronto ou personalize para criar um presente único.</p>{products.length?<div className="grid storeGrid">{products.map((p,i)=><article key={p.id}><div className={'pic p'+(i%4)} style={p.imagens?.[0]?{background:'#fff'}:undefined}>{p.imagens?.[0]?<img src={p.imagens[0]} alt={p.nome} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<span>CK</span>}<i>{p.destaque?'DESTAQUE':p.categoria}</i></div><div className="cardBody"><h3>{p.nome}</h3><p>{p.descricao||'Produto CaneKids.'}</p><small>R$ {Number(p.preco).toFixed(2).replace('.',',')}</small><Link href={p.tipo==='comum'?'/produto/'+p.id:'/produto?id='+p.id}>{p.tipo==='comum'?'Ver produto':'Personalizar'} →</Link></div></article>)}</div>:<div style={{padding:'34px',textAlign:'center',background:'#f7fafc',borderRadius:18,color:'#60788a'}}>Cadastre e publique seus produtos no Admin para montar esta vitrine.</div>}</section>
 <section className="homeTrust"><div><b>Compra segura</b><span>Pagamento protegido</span></div><div><b>Produção cuidadosa</b><span>Conferimos seu pedido antes do envio</span></div><div><b>Atendimento humano</b><span>Fale conosco quando precisar</span></div><div><b>Personalização fácil</b><span>Crie direto pelo site</span></div></section><section className="qr qrFeature" id="qr"><div><span className="eyebrow">CANEKIDS + DIZECODE</span><h2>O presente termina na embalagem. A experiência não.</h2><p>Adicione um QR Code ao produto e surpreenda com vídeo, fotos, áudio ou uma mensagem especial.</p><Link className="primary inlineBtn" href="/produto">Criar presente com QR</Link></div><div className="qrDemo"><div><b>1. Presenteie</b><p>O QR vai aplicado ao produto.</p><b>2. Escaneie</b><p>Não precisa instalar aplicativo.</p><b>3. Emocione</b><p>O conteúdo aparece no celular.</p></div></div></section>
 <section className="how" id="como"><div><span className="eyebrow">COMPRAR É SIMPLES</span><h2>Pronto ou personalizado. Você escolhe.</h2><p>Encontre um modelo na vitrine ou comece uma personalização.</p></div><ol><li><b>1</b><span><strong>Escolha o presente</strong>Navegue pelas categorias.</span></li><li><b>2</b><span><strong>Personalize se quiser</strong>Adicione foto, nome, frase e QR Code.</span></li><li><b>3</b><span><strong>Confira os detalhes</strong>Revise antes da produção.</span></li><li><b>4</b><span><strong>Receba em casa</strong>Escolha a entrega no checkout.</span></li></ol></section>
 <section className="socialProof"><span className="eyebrow">INSPIRAÇÃO PARA SUA ESCOLHA</span><h2>Presentes feitos para momentos especiais.</h2><div><article><b>Para quem ama guardar lembranças</b><p>Transforme fotos, nomes e mensagens em um presente que pode ser usado todos os dias.</p></article><article><b>Uma experiência além da caneca</b><p>Com DizeCode, o presente também pode revelar vídeo, áudio, fotos ou uma mensagem pelo celular.</p></article><article><b>Do seu jeito</b><p>Escolha entre produtos prontos ou use o personalizador para criar uma composição exclusiva.</p></article></div></section><section className="cta" id="contato"><h2>Não encontrou o que imaginou?</h2><p>Conte sua ideia. A CaneKids pode ajudar a transformar em um presente personalizado.</p><a href="https://wa.me/5541998621723">Falar com a CaneKids no WhatsApp</a></section><footer><div className="logo"><b>Cane</b><strong>Kids</strong></div><p>Presentes, canecas e personalizados para guardar momentos.</p><small>© 2026 CaneKids • Brasil</small></footer></main>
}