'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import {supabase} from '../../../lib/supabase';
export default function ProdutoComum(){const {id}=useParams<{id:string}>();const [p,setP]=useState<any>(null),[loading,setLoading]=useState(true),[selected,setSelected]=useState(0),[video,setVideo]=useState('');
useEffect(()=>{async function load(){if(!supabase||!id)return;const {data}=await supabase.rpc('storefront_products');setP((data||[]).find((x:any)=>x.id===id)||null);const {data:media}=await supabase.rpc('storefront_product_media',{p_id:id});setVideo(media?.[0]?.video_url||'');setLoading(false)}load()},[id]);
if(loading)return <main><section style={{maxWidth:1100,margin:'60px auto',padding:24}}>Carregando produto...</section></main>;
if(!p)return <main><section style={{maxWidth:1100,margin:'60px auto',padding:24}}><h1>Produto não encontrado</h1><Link href="/">Voltar para a loja</Link></section></main>;
return <main><header><Link href="/" className="logo"><b>Cane</b><strong>Kids</strong></Link><nav><Link href="/">Início</Link><Link href="/carrinho">Sacola</Link></nav></header><section style={{maxWidth:1180,margin:'0 auto',padding:'46px 24px',display:'grid',gridTemplateColumns:'minmax(0,1.05fr) minmax(360px,.75fr)',gap:44,alignItems:'start'}}><div>{video&&selected===-1?<video src={video} controls playsInline style={{width:'100%',height:560,objectFit:'contain',background:'#111',borderRadius:22}}/>:p.imagens?.[selected]?<img src={p.imagens[selected]} alt={p.nome} style={{width:'100%',height:560,objectFit:'contain',background:'#f7f8fa',borderRadius:22}}/>:<div style={{height:500,background:'#f7f8fa',borderRadius:22,display:'grid',placeItems:'center'}}>Sem imagem</div>}<div style={{display:'flex',gap:10,marginTop:12,overflowX:'auto',paddingBottom:6}}>{video&&<button onClick={()=>setSelected(-1)} style={{minWidth:92,height:82,border:selected===-1 ? '2px solid #087bc1' : '1px solid #dbe5ec',borderRadius:10,background:'#123b59',color:'#fff',fontWeight:800,cursor:'pointer'}}>Vídeo</button>)}{(p.imagens||[]).map((x:string,i:number)=><button key={x} onClick={()=>setSelected(i)} style={{minWidth:92,height:82,padding:3,border:selected===i ? '2px solid #087bc1' : '1px solid #dbe5ec',borderRadius:10,background:'#fff',cursor:'pointer'}}><img src={x} alt={'Imagem '+(i+1)} style={{width:'100%',height:'100%',objectFit:'cover',borderRadius:7}}/></button>)}</div></div><div style={{background:'#fff',border:'1px solid #dbe5ec',borderRadius:18,padding:28}}><span style={{fontSize:12,fontWeight:800,color:'#087bc1'}}>{p.categoria}</span><h1 style={{fontSize:36,lineHeight:1.1,margin:'10px 0 14px'}}>{p.nome}</h1><p style={{color:'#60788a',fontSize:16,lineHeight:1.6}}>{p.descricao||'Produto CaneKids.'}</p><div style={{fontSize:30,fontWeight:900,margin:'24px 0'}}>R$ {Number(p.preco).toFixed(2).replace('.',',')}</div><div style={{fontSize:13,color:p.estoque>0?'#356a46':'#b42318',marginBottom:18}}>{p.estoque>0?p.estoque+' unidade(s) disponível(is)':'Produto indisponível'}</div><Link href={'/carrinho?produto='+encodeURIComponent(p.id)+'&nome='+encodeURIComponent(p.nome)+'&preco='+encodeURIComponent(p.preco)} style={{display:'block',textAlign:'center',background:p.estoque>0 ? '#ff176b' : '#aab7c0',color:'#fff',padding:'16px',borderRadius:10,fontWeight:800,textDecoration:'none',pointerEvents:p.estoque>0 ? 'auto' : 'none'}}>Adicionar à sacola • R$ {Number(p.preco).toFixed(2).replace('.',',')}</Link><div style={{fontSize:12,color:'#60788a',textAlign:'center',marginTop:12}}>Compra segura · Produto conferido antes do envio</div></div></section></main>}