'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
const vazio={titulo:'',subtitulo:'',etiqueta:'',texto_botao:'Ver produtos',link_botao:'#vitrine',ativo:false,ordem:'0'};
export default function Banners(){
 const [form,setForm]=useState<any>(vazio),[items,setItems]=useState<any[]>([]),[editando,setEditando]=useState<string|null>(null),[imagem,setImagem]=useState(''),[arquivo,setArquivo]=useState<File|null>(null),[msg,setMsg]=useState('');
 useEffect(()=>{carregar()},[]);
 async function carregar(){if(!supabase)return;const {data,error}=await supabase.rpc('admin_list_banners');if(error)setMsg(error.message);else setItems(data||[])}
 function change(e:any){const {name,value,type,checked}=e.target;setForm((f:any)=>({...f,[name]:type==='checkbox'?checked:value}))}
 async function salvar(e:any){e.preventDefault();if(!supabase)return;setMsg('');try{let url=imagem;if(arquivo){const ext=(arquivo.name.split('.').pop()||'jpg').toLowerCase();const path='banners/'+crypto.randomUUID()+'.'+ext;const {error}=await supabase.storage.from('product-images').upload(path,arquivo);if(error)throw error;url=supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl}const {error}=await supabase.rpc('admin_save_banner',{p_id:editando,p_titulo:form.titulo,p_subtitulo:form.subtitulo,p_etiqueta:form.etiqueta,p_texto_botao:form.texto_botao,p_link_botao:form.link_botao,p_imagem:url||null,p_ativo:form.ativo,p_ordem:Number(form.ordem||0)});if(error)throw error;setMsg('Banner salvo.');setForm(vazio);setImagem('');setArquivo(null);setEditando(null);carregar()}catch(err:any){setMsg('Não foi possível salvar: '+err.message)}}
 function editar(b:any){setEditando(b.id);setImagem(b.imagem||'');setArquivo(null);setForm({titulo:b.titulo,subtitulo:b.subtitulo||'',etiqueta:b.etiqueta||'',texto_botao:b.texto_botao||'Ver produtos',link_botao:b.link_botao||'#vitrine',ativo:!!b.ativo,ordem:String(b.ordem||0)})}
 async function excluir(id:string){if(!supabase||!confirm('Excluir este banner?'))return;const {error}=await supabase.rpc('admin_delete_banner',{p_id:id});if(error)setMsg(error.message);else carregar()}
 return <main style={{minHeight:'100vh',background:'#f6f8fb',color:'#123b59'}}><header style={header}><Link href="/admin" style={brand}>CaneKids Admin</Link><Link href="/">Ver loja</Link></header><section style={{maxWidth:1150,margin:'0 auto',padding:'42px 24px'}}><p style={eyebrow}>PÁGINA INICIAL</p><h1 style={{fontSize:38,margin:'5px 0'}}>Banners e vitrine</h1><p style={{color:'#60788a'}}>Troque a campanha principal da loja sem alterar o código.</p>{msg&&<div style={notice}>{msg}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr 400px',gap:24,alignItems:'start',marginTop:24}}><section style={card}><h2 style={{marginTop:0}}>Banners</h2>{items.length===0?<p style={{color:'#60788a'}}>Nenhum banner cadastrado.</p>:items.map(b=><div key={b.id} style={row}>{b.imagem?<img src={b.imagem} alt="" style={thumb}/>:<div style={{...thumb,background:'#eef3f6'}}/>}<div style={{flex:1}}><b>{b.titulo}</b><div style={{fontSize:13,color:'#60788a'}}>{b.ativo?'Ativo na Home':'Oculto'} · ordem {b.ordem}</div></div><button onClick={()=>editar(b)} style={button}>Editar</button><button onClick={()=>excluir(b.id)} style={{...button,color:'#b42318'}}>Excluir</button></div>)}</section><form onSubmit={salvar} style={card}><h2 style={{marginTop:0}}>{editando?'Editar banner':'Novo banner'}</h2><Field label="Chamada pequena"><input name="etiqueta" value={form.etiqueta} onChange={change} placeholder="PRESENTES PARA EMOCIONAR" style={input}/></Field><Field label="Título"><input name="titulo" value={form.titulo} onChange={change} required style={input}/></Field><Field label="Texto"><textarea name="subtitulo" value={form.subtitulo} onChange={change} style={{...input,minHeight:75}}/></Field><div style={two}><Field label="Texto do botão"><input name="texto_botao" value={form.texto_botao} onChange={change} style={input}/></Field><Field label="Destino do botão"><input name="link_botao" value={form.link_botao} onChange={change} style={input}/></Field></div><Field label="Imagem"><label style={upload}>Selecionar imagem<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setArquivo(e.target.files?.[0]||null)} style={{display:'none'}}/></label></Field>{(arquivo||imagem)&&<img src={arquivo?URL.createObjectURL(arquivo):imagem} alt="" style={{width:'100%',maxHeight:190,objectFit:'cover',borderRadius:10}}/>}<Field label="Ordem"><input name="ordem" type="number" value={form.ordem} onChange={change} style={input}/></Field><label style={check}><input type="checkbox" name="ativo" checked={form.ativo} onChange={change}/> Exibir na Home</label><button style={primary}>{editando?'Salvar alterações':'Salvar banner'}</button>{editando&&<button type="button" onClick={()=>{setEditando(null);setForm(vazio);setImagem('');setArquivo(null)}} style={{...button,width:'100%',marginTop:8}}>Cancelar</button>}</form></div></section></main>}
function Field({label,children}:any){return <label style={{display:'block',fontWeight:700,margin:'13px 0 6px'}}>{label}<div style={{marginTop:6}}>{children}</div></label>}
const header={padding:'18px 5%',background:'#fff',borderBottom:'1px solid #dbe5ec',display:'flex',justifyContent:'space-between'};const brand={fontWeight:800,color:'#123b59',textDecoration:'none'};const eyebrow={fontWeight:800,color:'#087bc1',letterSpacing:1.5,fontSize:12};const card={background:'#fff',border:'1px solid #dbe5ec',borderRadius:16,padding:22};const row={display:'flex',gap:10,alignItems:'center',padding:'14px 0',borderTop:'1px solid #edf2f5'};const thumb={width:92,height:58,objectFit:'cover' as const,borderRadius:8};const input={width:'100%',boxSizing:'border-box' as const,padding:'11px 12px',border:'1px solid #cbdbe6',borderRadius:9,fontSize:14};const button={border:'1px solid #cbdbe6',borderRadius:8,padding:'8px 10px',background:'#fff',cursor:'pointer'};const primary={width:'100%',border:0,borderRadius:10,padding:'14px',fontWeight:800,background:'#087bc1',color:'#fff',cursor:'pointer'};const notice={marginTop:18,padding:'12px 14px',background:'#eef7fc',border:'1px solid #c9e4f4',borderRadius:10};const two={display:'grid',gridTemplateColumns:'1fr 1fr',gap:10};const upload={display:'block',padding:16,textAlign:'center' as const,border:'2px dashed #b9cedc',borderRadius:10,color:'#087bc1',cursor:'pointer'};const check={display:'flex',gap:8,margin:'15px 0',fontWeight:600};