'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {supabase} from '../../../lib/supabase';
const vazio={nome:'',descricao:'',ativo:true,ordem:'0'};
export default function Categorias(){
 const [form,setForm]=useState<any>(vazio),[items,setItems]=useState<any[]>([]),[editando,setEditando]=useState<string|null>(null),[msg,setMsg]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{carregar()},[]);
 async function carregar(){if(!supabase)return;setLoading(true);const {data,error}=await supabase.rpc('admin_list_categories');if(error)setMsg(error.message);else setItems(data||[]);setLoading(false)}
 function change(e:any){const {name,value,type,checked}=e.target;setForm((f:any)=>({...f,[name]:type==='checkbox'?checked:value}))}
 function slugify(s:string){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
 async function salvar(e:any){e.preventDefault();if(!supabase)return;setMsg('');const {error}=await supabase.rpc('admin_save_category',{p_id:editando,p_nome:form.nome,p_slug:slugify(form.nome),p_descricao:form.descricao||'',p_ativo:form.ativo,p_ordem:Number(form.ordem||0)});if(error)setMsg('Não foi possível salvar: '+error.message);else{setMsg('Categoria salva.');setForm(vazio);setEditando(null);carregar()}}
 function editar(c:any){setEditando(c.id);setForm({nome:c.nome,descricao:c.descricao||'',ativo:!!c.ativo,ordem:String(c.ordem||0)})}
 async function excluir(id:string){if(!supabase||!confirm('Excluir esta categoria?'))return;const {error}=await supabase.rpc('admin_delete_category',{p_id:id});if(error)setMsg('Não foi possível excluir: '+error.message);else carregar()}
 return <main style={{minHeight:'100vh',background:'#f6f8fb',color:'#123b59'}}><header style={{padding:'18px 5%',background:'#fff',borderBottom:'1px solid #dbe5ec',display:'flex',justifyContent:'space-between'}}><Link href="/admin" style={{fontWeight:800,textDecoration:'none',color:'#123b59'}}>CaneKids Admin</Link><Link href="/">Ver loja</Link></header><section style={{maxWidth:1100,margin:'0 auto',padding:'42px 24px'}}><p style={{fontSize:12,fontWeight:800,color:'#087bc1',letterSpacing:1.4}}>CATÁLOGO</p><h1 style={{fontSize:38,margin:'5px 0'}}>Categorias</h1><p style={{color:'#60788a'}}>Crie e organize as linhas que serão usadas no cadastro dos produtos.</p>{msg&&<div style={notice}>{msg}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr 380px',gap:24,alignItems:'start',marginTop:24}}><section style={card}><h2 style={{marginTop:0}}>Categorias cadastradas</h2>{loading?<p>Carregando...</p>:items.map(c=><div key={c.id} style={row}><div style={{flex:1}}><b>{c.nome}</b><div style={{fontSize:13,color:'#60788a',marginTop:4}}>{c.descricao||'Sem descrição'} · ordem {c.ordem}</div><div style={{fontSize:12,marginTop:4}}>{c.ativo?'Ativa':'Oculta'}</div></div><button onClick={()=>editar(c)} style={button}>Editar</button><button onClick={()=>excluir(c.id)} style={{...button,color:'#b42318'}}>Excluir</button></div>)}</section><form onSubmit={salvar} style={card}><h2 style={{marginTop:0}}>{editando?'Editar categoria':'Nova categoria'}</h2><Field label="Nome"><input name="nome" value={form.nome} onChange={change} required style={input}/></Field><Field label="Descrição"><textarea name="descricao" value={form.descricao} onChange={change} style={{...input,minHeight:80}}/></Field><Field label="Ordem de exibição"><input type="number" name="ordem" value={form.ordem} onChange={change} style={input}/></Field><label style={{display:'flex',gap:8,margin:'16px 0',fontWeight:600}}><input type="checkbox" name="ativo" checked={form.ativo} onChange={change}/> Categoria ativa</label><button style={primary}>{editando?'Salvar alterações':'Criar categoria'}</button>{editando&&<button type="button" onClick={()=>{setEditando(null);setForm(vazio)}} style={{...button,width:'100%',marginTop:8}}>Cancelar</button>}</form></div></section></main>}
function Field({label,children}:any){return <label style={{display:'block',fontWeight:700,margin:'13px 0 6px'}}>{label}<div style={{marginTop:6}}>{children}</div></label>}
const card={background:'#fff',border:'1px solid #dbe5ec',borderRadius:16,padding:22};const row={display:'flex',alignItems:'center',gap:8,padding:'15px 0',borderTop:'1px solid #edf2f5'};const input={width:'100%',boxSizing:'border-box' as const,padding:'11px 12px',border:'1px solid #cbdbe6',borderRadius:9,fontSize:14};const button={border:'1px solid #cbdbe6',borderRadius:8,padding:'8px 10px',background:'#fff',cursor:'pointer'};const primary={width:'100%',border:0,borderRadius:10,padding:'14px 18px',fontWeight:800,background:'#087bc1',color:'#fff',cursor:'pointer'};const notice={marginTop:18,padding:'12px 14px',background:'#eef7fc',border:'1px solid #c9e4f4',borderRadius:10};